[server]
headless = true
address = "127.0.0.1"
port = 5000
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#6E45E1"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[browser]
gatherUsageStats = false
